services:
  mysql:
    image: mysql:8
    container_name: taskmgr-mysql
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - "./.data/mysql:/var/lib/mysql"
      - "./.data/mysql-init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taskmgr
      MYSQL_USER: taskmgr
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'